# 1. 데이터베이스 연결 설정
# localhost:3306/뒤의 이름은 아까 만든 DB 이름과 같아야 합니다.
spring.datasource.url=jdbc:mysql://localhost:3306/trading_db?serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1556

# 2. JPA/Hibernate 설정 (Java 객체와 DB 테이블 연결 도구)
# update: 서버 실행 시 Java 코드와 DB 테이블 구조를 비교해서 자동으로 맞춰줍니다.
spring.jpa.hibernate.ddl-auto=update
# 서버가 실행하는 SQL 명령어를 터미널 콘솔에 예쁘게 보여줍니다.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true